### ISSUE TITLE
Deployment improvement

### ISSUE THREAD

**Issue by osaddict** [emccode/fuel-plugin-scaleio-cinder-test#2]
Break deployment into two steps:
Enter just admin/password and IPs
  Query ScaleIO cluster for protection domain and pools
Give multi-select options for customers wanting to have OpenStack use multiple Protection domains and Pools.

Even better, if possible, is to have step 1 be just user/pass and gateway and gather the other IP info from the query as well.

**Comment by msalem2** [comment]
Great, thank you for the feedback. As you know the repo is moved to https://github.com/openstack/fuel-plugin-scaleio-cinder. if you have any other idea or feedback please post it there.

**Comment by osaddict** [comment]
Sorry. Will add to the non-test one.

**Comment by osaddict** [comment]
I don't see an git issues tab on https://github.com/openstack/fuel-plugin-scaleio-cinder. Am I missing something or do I need some special permissions?

**Comment by msalem2** [comment]
Good point, I believe with openstack they use https://launchpad.net/openstack to record the issues. This repo is not watched so if you have any immediate feedback you can email us.
